# Generated by Django 5.1.7 on 2025-03-20 21:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('indexes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Initial investment amount', max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current value of the investment', max_digits=20)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current profit or loss', max_digits=20)),
                ('profit_loss_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profit/Loss as a percentage', max_digits=10)),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(help_text='Unique identifier for the investment', max_length=255, unique=True)),
                ('withdrawal_eligible', models.BooleanField(default=False, help_text='Whether the investment can be withdrawn')),
                ('lock_period_end', models.DateTimeField(help_text='Date when the investment can be withdrawn')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='indexes.index')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-investment_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount allocated to this company', max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Number of shares/units', max_digits=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Price at time of purchase', max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Current market price', max_digits=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Percentage of total investment', max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_positions', to='companies.company')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='investments.investment')),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_352b49_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['status', 'lock_period_end'], name='investments_status_9a0714_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentposition',
            index=models.Index(fields=['investment', 'company'], name='investments_investm_e96d24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='investmentposition',
            unique_together={('investment', 'company')},
        ),
    ]
