# Generated by Django 5.1.7 on 2025-03-21 11:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_investment_unique_together_and_more'),
        ('indexes', '0002_index_investment_end_date_and_more'),
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-investment_date'], 'verbose_name': 'Investment', 'verbose_name_plural': 'Investments'},
        ),
        migrations.AlterModelOptions(
            name='investmentposition',
            options={'ordering': ['-weight'], 'verbose_name': 'Investment Position', 'verbose_name_plural': 'Investment Positions'},
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Initial investment amount', max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Investment Amount'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current value of the investment', max_digits=20, null=True, verbose_name='Current Value'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='indexes.index', verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Investment Date'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='lock_period_end',
            field=models.DateTimeField(blank=True, help_text='Date when the investment can be withdrawn', null=True, verbose_name='Lock Period End'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current profit or loss', max_digits=20, verbose_name='Profit/Loss'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='profit_loss_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profit/Loss as a percentage', max_digits=10, verbose_name='Profit/Loss Percentage'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('VOTED', 'Voted'), ('LOCKED', 'Locked'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, help_text='Unique identifier for the investment', max_length=255, unique=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='withdrawal_eligible',
            field=models.BooleanField(default=False, help_text='Whether the investment can be withdrawn', verbose_name='Withdrawal Eligible'),
        ),
        migrations.AlterField(
            model_name='investmentposition',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount allocated to this company', max_digits=20, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='investmentposition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_positions', to='companies.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='investmentposition',
            name='current_price',
            field=models.DecimalField(decimal_places=2, help_text='Current market price', max_digits=20, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='investmentposition',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='investments.investment', verbose_name='Investment'),
        ),
        migrations.AlterField(
            model_name='investmentposition',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='investmentposition',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Price at time of purchase', max_digits=20, verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='investmentposition',
            name='quantity',
            field=models.DecimalField(decimal_places=8, help_text='Number of shares/units', max_digits=20, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='investmentposition',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Percentage of total investment', max_digits=5, verbose_name='Weight'),
        ),
    ]
