# Generated by Django 5.1.7 on 2025-03-20 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Index Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('min_companies', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Minimum Companies')),
                ('max_companies', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Maximum Companies')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(to='companies.company', verbose_name='Companies')),
            ],
            options={
                'verbose_name': 'Index',
                'verbose_name_plural': 'Indexes',
                'db_table': 'indexes',
                'ordering': ['-created_at'],
            },
        ),
    ]
