# Generated by Django 5.1.7 on 2025-03-21 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='investment_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Investment End Date'),
        ),
        migrations.AddField(
            model_name='index',
            name='investment_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Investment Start Date'),
        ),
        migrations.AddField(
            model_name='index',
            name='lock_period_months',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Lock Period (months)'),
        ),
        migrations.AddField(
            model_name='index',
            name='max_votes_per_user',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Votes per User'),
        ),
        migrations.AddField(
            model_name='index',
            name='min_votes_per_user',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Votes per User'),
        ),
        migrations.AddField(
            model_name='index',
            name='voting_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Voting End Date'),
        ),
        migrations.AddField(
            model_name='index',
            name='voting_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Voting Start Date'),
        ),
        migrations.AlterField(
            model_name='index',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('voting', 'Voting Period'), ('closed', 'Closed'), ('executed', 'Executed'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
