# Generated by Django 5.1.7 on 2025-03-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0002_index_investment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
