# Generated by Django 5.1.7 on 2025-03-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0003_alter_index_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('executed', 'Executed'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
