# Generated by Django 5.1.7 on 2025-03-21 11:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_company_sector_binanceintegration_investmentindex_and_more'),
        ('indexes', '0001_initial'),
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('min_votes_required', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Votes Required')),
                ('max_votes_allowed', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Votes Allowed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('min_investors', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Investors Required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voting_session', to='indexes.index', verbose_name='Index')),
            ],
            options={
                'verbose_name': 'Voting Session',
                'verbose_name_plural': 'Voting Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VotingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.PositiveIntegerField(default=0, verbose_name='Vote Count')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Percentage of Total Votes')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='Rank')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_results', to='companies.company', verbose_name='Company')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='voting.votingsession', verbose_name='Voting Session')),
            ],
            options={
                'verbose_name': 'Voting Result',
                'verbose_name_plural': 'Voting Results',
                'ordering': ['rank'],
                'unique_together': {('session', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='companies.company', verbose_name='Company')),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='investments.investment', verbose_name='Investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.votingsession', verbose_name='Voting Session')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'user'], name='voting_vote_session_9226b3_idx'), models.Index(fields=['session', 'company'], name='voting_vote_session_83eb63_idx')],
                'unique_together': {('session', 'user', 'company')},
            },
        ),
    ]
