# Generated by Django 5.1.7 on 2025-03-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='vote',
                    name='session_id',
                    field=models.IntegerField(blank=True, null=True),
                ),
            ],
        ),
    ]
