# Generated by Django 5.1.7 on 2025-03-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('symbol', models.CharField(max_length=50, unique=True, verbose_name='Trading Symbol')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Current Price')),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Market Cap')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
    ]
