# Generated by Django 5.1.7 on 2025-03-21 07:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.CharField(choices=[('TECH', 'Technology'), ('FIN', 'Financial'), ('HEALTH', 'Healthcare'), ('CONS', 'Consumer'), ('IND', 'Industrial'), ('ENERGY', 'Energy'), ('MAT', 'Materials'), ('UTIL', 'Utilities'), ('REAL', 'Real Estate'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Sector'),
        ),
        migrations.CreateModel(
            name='BinanceIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(max_length=255, verbose_name='API Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Binance Integration',
                'verbose_name_plural': 'Binance Integrations',
                'db_table': 'binance_integrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Index Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('min_companies', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Minimum Companies')),
                ('max_companies', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Maximum Companies')),
                ('min_votes_per_user', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Votes per User')),
                ('max_votes_per_user', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Maximum Votes per User')),
                ('investment_start_date', models.DateTimeField(verbose_name='Investment Start Date')),
                ('investment_end_date', models.DateTimeField(verbose_name='Investment End Date')),
                ('voting_start_date', models.DateTimeField(verbose_name='Voting Start Date')),
                ('voting_end_date', models.DateTimeField(verbose_name='Voting End Date')),
                ('lock_period_months', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Lock Period (months)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('voting', 'Voting Period'), ('closed', 'Closed'), ('executed', 'Executed')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(to='companies.company', verbose_name='Companies')),
            ],
            options={
                'verbose_name': 'Investment Index',
                'verbose_name_plural': 'Investment Indexes',
                'db_table': 'investment_indexes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Investment Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('voted', 'Voted'), ('locked', 'Locked'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.investmentindex', verbose_name='Investment Index')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'db_table': 'investments',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Company')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.investment', verbose_name='Investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'db_table': 'votes',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'investment', 'company')},
            },
        ),
    ]
