# Generated by Django 5.1.7 on 2025-03-21 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_sector_binanceintegration_investmentindex_and_more'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='investment',
            name='index',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.AlterField(
            model_name='vote',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investment', verbose_name='Investment'),
        ),
        migrations.RemoveField(
            model_name='investmentindex',
            name='companies',
        ),
        migrations.DeleteModel(
            name='BinanceIntegration',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='InvestmentIndex',
        ),
    ]
