# Generated by Django 5.1.7 on 2025-03-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Initial Price'),
        ),
        migrations.AddField(
            model_name='company',
            name='price_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price Change'),
        ),
    ]
