# Generated by Django 5.1.7 on 2025-03-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(max_length=50, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
